import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { makeWorkspace, runDetector, keysOf, assertEvidence } from './helpers/wsmap-fixtures.mjs';
import detector from '../src/core/workspace-map/detectors/api-proto.mjs';

const PROTO = `syntax = "proto3";
// service Commented { rpc Nope(A) returns (B); }
package acme.billing.v1;

service Billing {
  option (google.api.default_host) = "billing.acme.io";
  rpc GetInvoice(GetInvoiceRequest) returns (Invoice) {
    option (google.api.http) = { get: "/v1/invoices/{id}" };
  }
  rpc ListInvoices (ListInvoicesRequest) returns (stream Invoice);
}

service Admin {
  rpc Purge(PurgeRequest) returns (PurgeReply);
}
`;

// What protoc-gen-go-grpc writes (committed in most Go repos): it names BOTH sides of each service.
const GEN_GO = `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: billing.proto

package billingv1

func NewBillingClient(cc grpc.ClientConnInterface) BillingClient { return &billingClient{cc} }

type UnimplementedBillingServer struct{}

func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) { s.RegisterService(&Billing_ServiceDesc, srv) }

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient { return &adminClient{cc} }

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) { s.RegisterService(&Admin_ServiceDesc, srv) }
`;

// Generated code alone (the .proto lives in a shared protos repo): its full method names define the services.
const GEN_GO_FULL = `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package billingv1

const (
\tBilling_GetInvoice_FullMethodName   = "/acme.billing.v1.Billing/GetInvoice"
\tBilling_ListInvoices_FullMethodName = "/acme.billing.v1.Billing/ListInvoices"
\tAdmin_Purge_FullMethodName          = "/acme.billing.v1.Admin/Purge"
)

func NewBillingClient(cc grpc.ClientConnInterface) BillingClient { return &billingClient{cc} }

func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) { s.RegisterService(&Billing_ServiceDesc, srv) }
`;
const GEN_PY = `# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
class BillingStub(object):
    def __init__(self, channel):
        self.GetInvoice = channel.unary_unary('/acme.billing.v1.Billing/GetInvoice')
`;

let ws;
before(async () => {
  ws = await makeWorkspace({
    // Go server implementing Billing; no hint for Admin.
    billing: { 'proto/billing.proto': PROTO, 'internal/server.go': 'type srv struct{ pb.UnimplementedBillingServer }\nfunc main() { pb.RegisterBillingServer(s, &srv{}) }\n' },
    // Python client of Billing via the shared proto; Java client of a service with no local proto.
    web: {
      'protos/billing.proto': PROTO.replace(/\n/g, '\r\n'),
      'app/client.py': 'import billing_pb2_grpc\nstub = billing_pb2_grpc.BillingStub(channel)\n',
      'src/Ledger.java': 'var s = LedgerGrpc.newBlockingStub(channel);\n',
      'app/audit.py': 'import audit_pb2_grpc\nstub = audit_pb2_grpc.AuditStub(channel)\n',
      'public/vendor.js': `var x=${'1+'.repeat(700)}1;RegisterBillingServer(s);\n`, // a minified bundle: never a hint
    },
    // a contracts repo: the .proto alone.
    contracts: { 'billing.proto': PROTO },
    gogen: { 'gen/billingv1/billing_grpc.pb.go': GEN_GO_FULL, 'client.go': 'package web\nfunc New(conn *grpc.ClientConn) { billingv1.NewBillingClient(conn) }\n' },
    pygen: { 'app/billing_pb2_grpc.py': GEN_PY, 'app/server.py': 'import billing_pb2_grpc\nbilling_pb2_grpc.add_BillingServicer_to_server(Svc(), server)\n' },
    csharp: { 'Billing.proto': PROTO, 'BillingService.cs': 'public class BillingImpl : Billing.BillingBase { }\n', 'Program.cs': 'var c = new Billing.BillingClient(ch);\n' },
    // Go server and Go client, both with the generated code committed; the client's test runs an in-process fake server.
    gosvc: { 'proto/billing.proto': PROTO, 'gen/billingv1/billing_grpc.pb.go': GEN_GO, 'cmd/server.go': 'package main\nfunc main() { billingv1.RegisterBillingServer(s, &srv{}) }\n' },
    goclient: {
      'proto/billing.proto': PROTO, 'gen/billingv1/billing_grpc.pb.go': GEN_GO,
      'client.go': 'package web\nfunc New(conn *grpc.ClientConn) { billingv1.NewBillingClient(conn) }\n',
      'client_test.go': 'package web\nfunc TestClient(t *testing.T) { billingv1.RegisterBillingServer(s, &fakeBilling{}) }\n',
    },
  });
});
after(() => ws.cleanup());
const member = (k) => ws.members.find((m) => m.key === k);

test('api-proto: a server hint → provides one fact per rpc (package.Service/Method); comments ignored', async () => {
  const r = await runDetector(detector, member('billing'), ws.members);
  assert.deepEqual(keysOf(r, 'grpc', 'provides'), ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices']);
  const g = r.facts.find((f) => f.key.endsWith('/GetInvoice'));
  assert.deepEqual([g.line, g.match, g.detail], [7, 'GetInvoice', 'server internal/server.go:1']);
  assert.deepEqual(keysOf(r, 'grpc', 'consumes'), [], 'Admin has no hint here: no direction, no fact');
  assert.deepEqual(r.unresolved.map((u) => [u.raw, u.reason, u.line]), [['acme.billing.v1.Admin (1 rpc)', 'grpc service without a server or client hint', 13]]);
  assertEvidence(member('billing'), r);
});

test('api-proto: a client stub hint → consumes (exact); a stub with no local .proto (Java, Python) → unresolved', async () => {
  const r = await runDetector(detector, member('web'), ws.members);
  const billing = r.facts.filter((f) => f.key.startsWith('acme.billing.v1.Billing/'));
  assert.ok(billing.length === 2 && billing.every((f) => f.dir === 'consumes' && f.confidence === 'exact'));
  assert.equal(billing[0].detail, 'client app/client.py:2');
  assert.deepEqual(r.unresolved.map((u) => [u.raw, u.reason, u.line]), [['acme.billing.v1.Admin (1 rpc)', 'grpc service without a server or client hint', 13],
    ['audit_pb2_grpc.AuditStub', 'grpc client without a local .proto', 2], ['LedgerGrpc.newBlockingStub', 'grpc client without a local .proto', 1]]);
  assertEvidence(member('web'), r);
});

test('api-proto: a .proto with no hints at all (a contracts repo) → unresolved, no facts', async () => {
  const r = await runDetector(detector, member('contracts'), ws.members);
  assert.deepEqual(r.facts, []);
  assert.deepEqual(r.unresolved.map((u) => u.raw), ['acme.billing.v1.Billing (2 rpc)', 'acme.billing.v1.Admin (1 rpc)']);
});

test('api-proto: generated code and test fakes are no hints — a Go client never "provides" the service it calls', async () => {
  const svc = await runDetector(detector, member('gosvc'), ws.members);
  assert.deepEqual([keysOf(svc, 'grpc', 'provides'), keysOf(svc, 'grpc', 'consumes')], [['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices'], []]);
  assert.equal(svc.facts[0].detail, 'server cmd/server.go:2', 'the hint is the member\'s own registration, not the generated RegisterBillingServer');
  const client = await runDetector(detector, member('goclient'), ws.members);
  assert.deepEqual([keysOf(client, 'grpc', 'provides'), keysOf(client, 'grpc', 'consumes')], [[], ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices']]);
  assert.deepEqual(client.unresolved.map((u) => u.raw), ['acme.billing.v1.Admin (1 rpc)'], 'Admin: only the generated code names it');
});

test('api-proto: with no local .proto, vendored generated code defines the services this member serves or calls', async () => {
  const go = await runDetector(detector, member('gogen'), ws.members);
  assert.deepEqual([keysOf(go, 'grpc', 'provides'), keysOf(go, 'grpc', 'consumes')], [[], ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices']]);
  const f = go.facts[0];
  assert.deepEqual([f.file, f.line, f.match, f.detail], ['gen/billingv1/billing_grpc.pb.go', 5, '/acme.billing.v1.Billing/GetInvoice', 'client client.go:2 (generated code)']);
  assert.deepEqual(go.unresolved, [], 'Admin: generated, but neither served nor called here — silent');
  const py = await runDetector(detector, member('pygen'), ws.members);
  assert.deepEqual([keysOf(py, 'grpc', 'provides'), keysOf(py, 'grpc', 'consumes')], [['acme.billing.v1.Billing/GetInvoice'], []]);
  assertEvidence(member('gogen'), go);
  assertEvidence(member('pygen'), py);
});

test('api-proto: C# server base + client in one member → both provides and consumes', async () => {
  const r = await runDetector(detector, member('csharp'), ws.members);
  assert.equal(keysOf(r, 'grpc', 'provides').length, 2);
  assert.ok(keysOf(r, 'grpc', 'consumes').includes('acme.billing.v1.Billing/GetInvoice'));
});

// buf output of a whole module: one bare service name (`Admin`) in two generated packages.
const genAdmin = (pkg, goPkg, method) => `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage ${goPkg}\n\nconst Admin_${method}_FullMethodName = "/${pkg}.Admin/${method}"\n`;

test('api-proto: one service name in two generated packages — the caller\'s qualifier picks one, else unresolved (never both)', async () => {
  const gen = { 'gen/billing/v1/admin_grpc.pb.go': genAdmin('acme.billing.v1', 'billingv1', 'Refund'), 'gen/catalog/v1/admin_grpc.pb.go': genAdmin('acme.catalog.v1', 'catalogv1', 'Reindex') };
  const w = await makeWorkspace({
    orders: { ...gen, 'client.go': 'package orders\nimport billingv1 "acme/gen/billing/v1"\nfunc c() { billingv1.NewAdminClient(conn) }\n' },
    aliased: { ...gen, 'client.go': 'package orders\nimport (\n\tpb "acme/gen/catalog/v1"\n)\nfunc c() { pb.NewAdminClient(conn) }\n' },
    jobs: { ...gen, 'client.go': 'package jobs\nfunc c() { NewAdminClient(conn) }\n' },
  });
  try {
    const at = (k) => runDetector(detector, w.members.find((m) => m.key === k), w.members);
    assert.deepEqual(keysOf(await at('orders'), 'grpc', 'consumes'), ['acme.billing.v1.Admin/Refund'], 'the Go package clause');
    assert.deepEqual(keysOf(await at('aliased'), 'grpc', 'consumes'), ['acme.catalog.v1.Admin/Reindex'], 'an import alias names the generated dir');
    const jobs = await at('jobs');
    assert.deepEqual([jobs.facts, jobs.unresolved.map((u) => u.reason)], [[], ['grpc service name in more than one generated package']]);
  } finally { await w.cleanup(); }
});

test('api-proto: a hint is the member\'s own call or registration — not a comment, a same-named wrapper, a fake outside a test path or a DI .add(); a hand-written DO NOT EDIT keeps it', async () => {
  const w = await makeWorkspace({
    web: {
      'gen/billingv1/billing_grpc.pb.go': GEN_GO_FULL,
      'gen/paymentv1/payment_grpc.pb.go': '// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage paymentv1\nconst Payment_Charge_FullMethodName = "/acme.payment.v1.Payment/Charge"\n',
      'gen/users.ts': '// Code generated by protoc-gen-ts_proto. DO NOT EDIT.\nexport const UserDefinition = { path: "/acme.users.v1.User/GetUser" };\n',
      'client.go': 'package web\n// billing registers itself with billingv1.RegisterBillingServer at start\nfunc c() { billingv1.NewBillingClient(conn) }\n',
      'internal/testutil/fake_billing.go': 'package testutil\nfunc Start() { billingv1.RegisterBillingServer(s, &fake{}) }\n',
      'stripe.go': 'package web\nfunc NewPaymentClient(key string) *Stripe { return &Stripe{key} }\n',
      'src/app.ts': 'providers.add(UserService);\n',
    },
    billing: { 'gen/billingv1/billing_grpc.pb.go': GEN_GO_FULL, 'main.go': 'package main\n// DO NOT EDIT the port without updating deploy/k8s.\nfunc main() { billingv1.RegisterBillingServer(s, &srv{}) }\n' },
    users: { 'gen/users.ts': '// Code generated by protoc-gen-ts_proto. DO NOT EDIT.\nexport const UserServiceDefinition = { path: "/acme.users.v1.UserService/GetUser" };\n', 'src/server.ts': 'server.add(UserServiceDefinition, impl);\n' },
  });
  try {
    const at = (k) => runDetector(detector, w.members.find((m) => m.key === k), w.members);
    const web = await at('web');
    assert.deepEqual([keysOf(web, 'grpc', 'provides'), keysOf(web, 'grpc', 'consumes')], [[], ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices']]);
    assert.deepEqual(keysOf(await at('billing'), 'grpc', 'provides'), ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices'], 'a hand-written DO NOT EDIT is no generated-code stamp');
    assert.deepEqual(keysOf(await at('users'), 'grpc', 'provides'), ['acme.users.v1.UserService/GetUser'], 'nice-grpc server.add(XDefinition, impl) still serves');
    assertEvidence(w.members.find((m) => m.key === 'web'), web);
  } finally { await w.cleanup(); }
});

test('api-proto: ts-proto / grpc-js clients, grpc-gateway and vendored grpc-java / grpc-dotnet code are read', async () => {
  const w = await makeWorkspace({
    frontend: {
      'gen/cart.ts': '// Code generated by protoc-gen-ts_proto. DO NOT EDIT.\nexport const CartServiceService = { getCart: { path: "/oteldemo.CartService/GetCart" } };\n',
      'src/client.ts': 'const cart = new CartServiceClient(addr, credentials.createInsecure());\n',
    },
    gateway: { 'gen/billingv1/billing_grpc.pb.go': GEN_GO_FULL, 'main.go': 'package main\nfunc main() { billingv1.RegisterBillingHandlerFromEndpoint(ctx, mux, ep, opts) }\n' },
    jvm: {
      'gen/BillingGrpc.java': '@io.grpc.stub.annotations.GrpcGenerated\npublic final class BillingGrpc {\n  public static final String SERVICE_NAME = "acme.billing.v1.Billing";\n  getGetInvoiceMethod = generateFullMethodName(SERVICE_NAME, "GetInvoice");\n}\n',
      'src/Client.java': 'var stub = BillingGrpc.newBlockingStub(channel);\n',
    },
    dotnet: {
      'Generated/BillingGrpc.cs': '// <auto-generated>\npublic static partial class Billing {\n  static readonly string __ServiceName = "acme.billing.v1.Billing";\n  static readonly grpc::Method<A, B> __Method_GetInvoice = new grpc::Method<A, B>(grpc::MethodType.Unary, __ServiceName, "GetInvoice", m1, m2);\n}\n',
      'Program.cs': 'var c = new Billing.BillingClient(ch);\n',
    },
  });
  try {
    const at = (k) => runDetector(detector, w.members.find((m) => m.key === k), w.members);
    assert.deepEqual(keysOf(await at('frontend'), 'grpc', 'consumes'), ['oteldemo.CartService/GetCart']);
    assert.deepEqual(keysOf(await at('gateway'), 'grpc', 'consumes'), ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices']);
    const jvm = await at('jvm');
    assert.deepEqual([keysOf(jvm, 'grpc', 'consumes'), jvm.unresolved], [['acme.billing.v1.Billing/GetInvoice'], []]);
    assertEvidence(w.members.find((m) => m.key === 'jvm'), jvm);
    assert.deepEqual(keysOf(await at('dotnet'), 'grpc', 'consumes'), ['acme.billing.v1.Billing/GetInvoice'], 'grpc-dotnet: __ServiceName + the method name');
  } finally { await w.cleanup(); }
});

const GEN_GO_BILLING = `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package billingv1

const (
\tBilling_GetInvoice_FullMethodName   = "/acme.billing.v1.Billing/GetInvoice"
\tBilling_ListInvoices_FullMethodName = "/acme.billing.v1.Billing/ListInvoices"
)
`;
const atMember = (w, k) => runDetector(detector, w.members.find((m) => m.key === k), w.members);

// C4-01: the local-.proto path keyed services by bare name, so one hint consumed EVERY package's service of that name.
test('api-proto: one service name in two local .proto packages — the caller\'s qualifier picks one (go_package, Python module), else unresolved (never both)', async () => {
  const proto = (pkg, go, svc, rpc) => `syntax = "proto3";\npackage ${pkg};\noption go_package = "${go}";\nservice ${svc} {\n  rpc ${rpc}(A) returns (B);\n}\n`;
  const versions = { 'protos/acme/billing/v1/billing.proto': proto('acme.billing.v1', 'github.com/acme/gen/billing/v1;billingv1', 'Billing', 'GetInvoice'),
    'protos/acme/billing/v2/billing.proto': proto('acme.billing.v2', 'github.com/acme/gen/billing/v2;billingv2', 'Billing', 'GetInvoiceV2') };
  const admins = { 'protos/billing.proto': proto('acme.billing.v1', 'github.com/acme/gen/billing/pb;pb', 'Admin', 'Refund'),
    'protos/catalog.proto': proto('acme.catalog.v1', 'github.com/acme/gen/catalog/pb;pb', 'Admin', 'Reindex') };
  const w = await makeWorkspace({
    goclause: { ...versions, 'client.go': 'package web\nfunc c() { billingv1.NewBillingClient(conn) }\n' },
    goimport: { ...admins, 'client.go': 'package web\nimport (\n\t"github.com/acme/gen/catalog/pb"\n)\nfunc c() { pb.NewAdminClient(conn) }\n' },
    py: { ...admins, 'app/client.py': 'from . import catalog_pb2_grpc\nstub = catalog_pb2_grpc.AdminStub(channel)\n' },
    jvm: { ...versions, 'src/Client.java': 'var s = BillingGrpc.newBlockingStub(channel);\n' },
    server: { ...versions, 'main.go': 'package main\nfunc main() { billingv2.RegisterBillingServer(s, &srv{}) }\n' },
    node: { ...versions, 'server.js': 'server.addService(proto.acme.billing.v1.Billing.service, impl);\n' },
  });
  try {
    assert.deepEqual(keysOf(await atMember(w, 'goclause'), 'grpc', 'consumes'), ['acme.billing.v1.Billing/GetInvoice'], 'the go_package name');
    const imp = await atMember(w, 'goimport');
    assert.deepEqual([keysOf(imp, 'grpc', 'consumes'), imp.unresolved], [['acme.catalog.v1.Admin/Reindex'], []], 'the go_package import path; the other package stays silent');
    assert.deepEqual(keysOf(await atMember(w, 'py'), 'grpc', 'consumes'), ['acme.catalog.v1.Admin/Reindex'], 'the Python module');
    const jvm = await atMember(w, 'jvm');
    assert.deepEqual([jvm.facts, jvm.unresolved.map((u) => [u.raw, u.reason])],
      [[], [['BillingGrpc.newBlockingStub (acme.billing.v1.Billing, acme.billing.v2.Billing)', 'grpc service name in more than one package']]]);
    const server = await atMember(w, 'server');
    assert.deepEqual([keysOf(server, 'grpc', 'provides'), keysOf(server, 'grpc', 'consumes')], [['acme.billing.v2.Billing/GetInvoiceV2'], []]);
    assert.deepEqual(keysOf(await atMember(w, 'node'), 'grpc', 'provides'), ['acme.billing.v1.Billing/GetInvoice'], 'a dotted path ending in the proto package');
    assertEvidence(w.members.find((m) => m.key === 'goimport'), imp);
  } finally { await w.cleanup(); }
});

// C4-02: a stub / fake server outside a test path made the client a second provider (every call to the real one ambiguous).
test('api-proto: a stub or fake SERVER by path (stubs/, *stub*/, fake.go, fakes.py, mockserver.go) is no server hint — a client stub there still is', async () => {
  const w = await makeWorkspace({
    goweb: {
      'gen/billingv1/billing_grpc.pb.go': GEN_GO_BILLING,
      'client.go': 'package web\nfunc c() { billingv1.NewBillingClient(conn) }\n',
      'stubs/billing/main.go': 'package main\nfunc main() { billingv1.RegisterBillingServer(s, &stubBilling{}) }\n',
      'internal/stubserver/server.go': 'package stubserver\nfunc Start() { billingv1.RegisterBillingServer(s, &ss{}) }\n',
      'billing/fake.go': 'package billing\nfunc StartFake() { billingv1.RegisterBillingServer(s, &fakeServer{}) }\n',
      'mockserver.go': 'package web\nfunc Mock() { billingv1.RegisterBillingServer(s, &m{}) }\n',
    },
    pyweb: {
      'app/billing_pb2_grpc.py': GEN_PY,
      'app/fakes.py': 'class FakeBilling(billing_pb2_grpc.BillingServicer):\n    pass\n',
      'app/stubs/billing.py': 'stub = billing_pb2_grpc.BillingStub(channel)\n',
    },
    billing: { 'gen/billingv1/billing_grpc.pb.go': GEN_GO_BILLING, 'cmd/server/main.go': 'package main\nfunc main() { billingv1.RegisterBillingServer(s, &srv{}) }\n' },
  });
  try {
    const go = await atMember(w, 'goweb');
    assert.deepEqual([keysOf(go, 'grpc', 'provides'), keysOf(go, 'grpc', 'consumes')], [[], ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices']]);
    const py = await atMember(w, 'pyweb');
    assert.deepEqual([keysOf(py, 'grpc', 'provides'), keysOf(py, 'grpc', 'consumes')], [[], ['acme.billing.v1.Billing/GetInvoice']], 'a client stub under stubs/ still calls');
    assert.deepEqual(keysOf(await atMember(w, 'billing'), 'grpc', 'provides'), ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices']);
  } finally { await w.cleanup(); }
});

// C4-03: two generated packages sharing one Go package clause (`package pb`, v1 + v2 as `package billing`).
test('api-proto: a package clause two generated packages share is narrowed by the file\'s imports', async () => {
  const gen = (goPkg, pkg, svc, rpc) => `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage ${goPkg}\n\nconst ${svc}_${rpc}_FullMethodName = "/${pkg}.${svc}/${rpc}"\n`;
  const w = await makeWorkspace({
    pbclause: {
      'gen/billing/pb/admin_grpc.pb.go': gen('pb', 'acme.billing.v1', 'Admin', 'Refund'), 'gen/catalog/pb/admin_grpc.pb.go': gen('pb', 'acme.catalog.v1', 'Admin', 'Reindex'),
      'client.go': 'package web\nimport (\n\t"context"\n\t"github.com/acme/app/gen/billing/pb"\n)\nfunc c() { pb.NewAdminClient(conn) }\n',
    },
    major: {
      'gen/billing/v1/billing_grpc.pb.go': gen('billing', 'acme.billing.v1', 'Billing', 'GetInvoice'), 'gen/billing/v2/billing_grpc.pb.go': gen('billing', 'acme.billing.v2', 'Billing', 'GetInvoiceV2'),
      'client.go': 'package web\nimport "github.com/acme/app/gen/billing/v2"\nfunc c() { billing.NewBillingClient(conn) }\n',
    },
  });
  try {
    assert.deepEqual(keysOf(await atMember(w, 'pbclause'), 'grpc', 'consumes'), ['acme.billing.v1.Admin/Refund'], 'an unaliased import whose last segment is the qualifier');
    assert.deepEqual(keysOf(await atMember(w, 'major'), 'grpc', 'consumes'), ['acme.billing.v2.Billing/GetInvoiceV2'], 'a /v2 import whose package clause is the qualifier');
  } finally { await w.cleanup(); }
});

// C4-04 / C4-05: comment blanking must not eat code after a JS regex literal; Node static codegen and the grpc-gateway tutorial.
test('api-proto: a regex literal with an escaped slash opens no comment; grpc-tools / ts-proto addService(XService, impl) serves, RegisterXHandler(ctx, mux, conn) calls', async () => {
  const CART = '// Code generated by protoc-gen-ts_proto. DO NOT EDIT.\nexport const CartServiceService = { getCart: { path: "/oteldemo.CartService/GetCart" } };\n';
  const GREETER = '// GENERATED CODE -- DO NOT EDIT!\nvar GreeterService = exports.GreeterService = { sayHello: { path: \'/helloworld.Greeter/SayHello\' } };\n';
  const w = await makeWorkspace({
    blockre: {
      'gen/cart.ts': CART,
      'src/a.ts': "const base = process.env.CART_ADDR.replace(/\\/*$/, '');\nconst cart = new CartServiceClient(base, credentials.createInsecure());\n",
    },
    lineres: {
      'gen/cart.ts': CART,
      'src/b.ts': "const a = addr.replace(/^https?:\\/\\//, ''); const c2 = new CartServiceClient(a, credentials.createInsecure());\n",
    },
    cart: { 'gen/cart.ts': CART, 'src/server.ts': 'server.addService(CartServiceService, new CartServer());\n' },
    greeter: { 'helloworld_grpc_pb.js': GREETER, 'greeter_server.js': 'server.addService(services.GreeterService, {sayHello: sayHello});\n' },
    gateway: { 'gen/billingv1/billing_grpc.pb.go': GEN_GO_BILLING, 'main.go': 'package main\nfunc main() { err = billingv1.RegisterBillingHandler(context.Background(), gwmux, conn) }\n' },
    connect: { 'gen/billingv1connect/billing.connect.go': '// Code generated by protoc-gen-connect-go. DO NOT EDIT.\npackage billingv1connect\nconst BillingGetInvoiceProcedure = "/acme.billing.v1.Billing/GetInvoice"\n', 'main.go': 'package main\nfunc main() { billingv1connect.RegisterBillingHandler(server, &srv{}) }\n' },
  });
  try {
    assert.deepEqual(keysOf(await atMember(w, 'blockre'), 'grpc', 'consumes'), ['oteldemo.CartService/GetCart'], '/\\/*$/ opens no block comment');
    assert.deepEqual(keysOf(await atMember(w, 'lineres'), 'grpc', 'consumes'), ['oteldemo.CartService/GetCart'], '/^https?:\\/\\// opens no line comment');
    assert.deepEqual(keysOf(await atMember(w, 'cart'), 'grpc', 'provides'), ['oteldemo.CartService/GetCart'], 'ts-proto grpc-js');
    assert.deepEqual(keysOf(await atMember(w, 'greeter'), 'grpc', 'provides'), ['helloworld.Greeter/SayHello'], 'grpc-tools static codegen');
    assert.deepEqual(keysOf(await atMember(w, 'gateway'), 'grpc', 'consumes'), ['acme.billing.v1.Billing/GetInvoice', 'acme.billing.v1.Billing/ListInvoices'], 'grpc-gateway RegisterXHandler');
    const connect = await atMember(w, 'connect');
    assert.deepEqual([keysOf(connect, 'grpc', 'provides'), keysOf(connect, 'grpc', 'consumes')], [['acme.billing.v1.Billing/GetInvoice'], []], 'connect-go xconnect.RegisterXHandler(server, impl) serves');
  } finally { await w.cleanup(); }
});

test('api-proto: RegisterXHandler(srv, impl) — go-micro, dubbo-go triple — registers a server, never a grpc-gateway client; (ctx, mux, conn) and a handler-list value are clients', async () => {
  const P = 'syntax = "proto3";\npackage acme.billing;\nservice Billing {\n  rpc Get(A) returns (B);\n}\n';
  const w = await makeWorkspace({
    micro: { 'proto/billing.proto': P, 'main.go': 'package main\nfunc main() { pb.RegisterBillingHandler(service.Server(), new(Billing)) }\n' },
    dubbo: { 'proto/billing.proto': P, 'main.go': 'package main\nfunc main() { _ = pb.RegisterBillingHandler(srv, &BillingProvider{}, server.WithInterface("x")) }\n' },
    gw: { 'proto/billing.proto': P, 'main.go': 'package main\nfunc main() {\n\t_ = pb.RegisterBillingHandler(\n\t\tr.Context(),\n\t\tmux,\n\t\tconn,\n\t)\n}\n' },
    list: { 'proto/billing.proto': P, 'gw.go': 'package main\nvar hs = []func(context.Context, *runtime.ServeMux, *grpc.ClientConn) error{\n\tpb.RegisterBillingHandler,\n}\n' },
  });
  try {
    assert.deepEqual(keysOf(await atMember(w, 'micro'), 'grpc', 'consumes'), [], 'go-micro server registration');
    assert.deepEqual(keysOf(await atMember(w, 'dubbo'), 'grpc', 'consumes'), [], 'dubbo-go triple server registration (with an option)');
    assert.deepEqual(keysOf(await atMember(w, 'gw'), 'grpc', 'consumes'), ['acme.billing.Billing/Get'], 'a gateway call whose first argument is a context');
    assert.deepEqual(keysOf(await atMember(w, 'list'), 'grpc', 'consumes'), ['acme.billing.Billing/Get'], 'a gateway handler list');
  } finally { await w.cleanup(); }
});

test('api-proto: one service in v1 and v2 local protos — buf managed mode (no go_package), a connect-go `…connect` package, an alias beside a shared tag, a Python / JVM import — picks the imported version; an import whose last two segments name two packages picks none', async () => {
  const proto = (v, rpc, go) => `syntax = "proto3";\npackage acme.billing.${v};\n${go ? `option go_package = "github.com/acme/gen/billing/${v};billing${v}";\n` : ''}service BillingService {\n  rpc ${rpc}(A) returns (B);\n}\n`;
  const both = (go) => ({ 'proto/acme/billing/v1/billing.proto': proto('v1', 'GetInvoice', go), 'proto/acme/billing/v2/billing.proto': proto('v2', 'GetInvoiceV2', go) });
  const org = (o, rpc) => `syntax = "proto3";\npackage ${o}.billing.v1;\nservice BillingService {\n  rpc ${rpc}(A) returns (B);\n}\n`;
  const w = await makeWorkspace({
    managed: { ...both(false), 'client.go': 'package main\nimport (\n\tbillingv2 "github.com/acme/app/gen/go/acme/billing/v2"\n)\nfunc c() { billingv2.NewBillingServiceClient(conn) }\n' },
    connect: { ...both(true), 'main.go': 'package main\nimport (\n\t"github.com/acme/gen/billing/v2/billingv2connect"\n)\nfunc main() { mux.Handle(billingv2connect.NewBillingServiceHandler(&srv{})) }\n' },
    connectManaged: { ...both(false), 'main.go': 'package main\nimport (\n\t"github.com/acme/app/gen/go/acme/billing/v2/billingv2connect"\n)\nfunc main() { c := billingv2connect.NewBillingServiceClient(http.DefaultClient, url) }\n' },
    kratos: {
      'api/billing/v1/billing.proto': 'syntax = "proto3";\npackage billing.v1;\noption go_package = "github.com/acme/api/billing/v1;v1";\nservice Billing {\n  rpc Get(A) returns (B);\n}\n',
      'api/catalog/v1/catalog.proto': 'syntax = "proto3";\npackage catalog.v1;\noption go_package = "github.com/acme/api/catalog/v1;v1";\nservice Billing {\n  rpc Other(A) returns (B);\n}\n',
      'client.go': 'package main\nimport (\n\tv1 "github.com/acme/api/billing/v1"\n\tcatv1 "github.com/acme/api/catalog/v1"\n)\nfunc c() { v1.NewBillingClient(conn); _ = catv1.X }\n',
    },
    py: { ...both(true), 'client.py': 'from acme.billing.v2 import billing_pb2_grpc as b\nstub = b.BillingServiceStub(channel)\n' },
    pyDotted: { ...both(true), 'client.py': 'import acme.billing.v2.billing_pb2_grpc as b2\nstub = b2.BillingServiceStub(channel)\n' },
    jvm: { ...both(true), 'src/main/java/Cli.java': 'import acme.billing.v2.BillingServiceGrpc;\nclass Cli { void c() { var s = BillingServiceGrpc.newBlockingStub(channel); } }\n' },
    twoOrgs: { 'proto/acme/billing/v1/billing.proto': org('acme', 'A'), 'proto/partner/billing/v1/billing.proto': org('partner', 'B'),
      'client.go': 'package main\nimport (\n\tbillingv1 "github.com/acme/app/gen/go/other/billing/v1"\n)\nfunc c() { billingv1.NewBillingServiceClient(conn) }\n' },
  });
  try {
    for (const k of ['managed', 'connectManaged', 'py', 'pyDotted', 'jvm']) {
      const r = await atMember(w, k);
      assert.deepEqual([keysOf(r, 'grpc', 'consumes'), r.unresolved.map((u) => u.reason)], [['acme.billing.v2.BillingService/GetInvoiceV2'], []], k);
    }
    assert.deepEqual(keysOf(await atMember(w, 'connect'), 'grpc', 'provides'), ['acme.billing.v2.BillingService/GetInvoiceV2'], 'connect');
    assert.deepEqual(keysOf(await atMember(w, 'kratos'), 'grpc', 'consumes'), ['billing.v1.Billing/Get'], 'the alias names one import; the `v1` tag names both');
    const two = await atMember(w, 'twoOrgs');
    assert.deepEqual([two.facts, two.unresolved.map((u) => u.reason)], [[], ['grpc service name in more than one package']], 'the loose last-two-segments pick never chooses between two packages');
  } finally { await w.cleanup(); }
});

test('api-proto: the qualifier pick matches an import path against the package dirs, never a join per suffix per hint (a 2 048-segment import called from 800 sites, 256 such imports narrowing a shared clause: 2 s)', () => {
  const proto = (v) => `syntax = "proto3";\npackage acme.billing.${v};\noption go_package = "github.com/acme/gen/billing/${v};pb";\nservice BillingService {\n  rpc Get${v}(A) returns (B);\n}\n`;
  const long = `${'a/'.repeat(2048)}v1`;
  const member = { key: 'm', name: 'm', dir: '/nonexistent', projectDir: '/nonexistent' };
  const ctx = { member, members: [member], files: [], state: {} };
  const t0 = performance.now();
  detector.detect({ rel: 'proto/acme/billing/v1/billing.proto', text: proto('v1') }, ctx);
  detector.detect({ rel: 'proto/acme/billing/v2/billing.proto', text: proto('v2') }, ctx);
  detector.detect({ rel: 'a-long.go', text: `package main\nimport (\n\tv1 "${long}"\n)\nfunc c() {\n${'\tv1.NewBillingServiceClient(c)\n'.repeat(800)}}\n` }, ctx);
  detector.detect({ rel: 'b-narrow.go', text: `package main\nimport (\n${Array.from({ length: 256 }, (_, i) => `\ta${i} "${'a/'.repeat(1900)}v1"`).join('\n')}\n)\nfunc c() { pb.NewBillingServiceClient(conn) }\n` }, ctx);
  detector.detect({ rel: 'c-ok.go', text: 'package main\nimport (\n\tbillingv2 "github.com/acme/gen/billing/v2"\n)\nfunc c() { billingv2.NewBillingServiceClient(conn) }\n' }, ctx);
  const out = detector.finish(ctx);
  const ms = performance.now() - t0;
  assert.deepEqual([out.facts.filter((f) => f.dir === 'consumes').map((f) => f.key), out.unresolved.map((u) => u.reason)], [['acme.billing.v2.BillingService/Getv2'], []]);
  assert.ok(ms < 2000, `api-proto took ${ms.toFixed(0)} ms (a join per import suffix per hint: ~12 s)`);
});
