// api-proto: .proto service definitions + generated-code hints in source files.
// Rule (per .proto service S in package P, one fact per rpc M, key 'P.S/M'):
//   provides  when this member has a SERVER hint for S (generated server base class /
//             registration: Go RegisterSServer / UnimplementedSServer, Java/Kotlin SImplBase,
//             Python add_SServicer_to_server / SServicer, C# S.SBase, Rust SServer::new,
//             connect-go NewSHandler, grpc-js addService(… S.service), nice-grpc add(SDefinition))
//   consumes  when this member has a CLIENT hint for S (Go NewSClient, Java SGrpc.new*Stub,
//             Python SStub / x_pb2_grpc.SStub, C# S.SClient, Rust SClient::connect, nice-grpc
//             createClient(SDefinition)), confidence 'exact'
//   neither   → one unresolved 'grpc service without a server or client hint' (decision P3-6)
//   A member may both provide and consume S (server + client hints) → both facts.
// Hints come only from the member's own code: a test path (a Go client test registering an
// in-process fake server) and generated code (protoc / buf output names both the server and the
// client of every service — `// Code generated … DO NOT EDIT.`, `<auto-generated>`, `@generated`,
// `@GrpcGenerated`) give none, and a minified JS bundle is skipped.
// A service no local .proto defines is taken from vendored generated code when the member serves or
// calls it: the full method names protoc / buf plugins write (`"/acme.billing.v1.Billing/GetInvoice"` —
// Go FullMethodName / Invoke, connect-go procedures, Python _pb2_grpc, grpc-js / ts-proto paths, tonic)
// define it, so a Go or Python service whose .proto lives in a shared protos repo still has its rpcs.
// Client hints for a service neither a .proto nor generated code defines → unresolved (package unknown).
// One bare service name in several packages — local .proto files or generated code alike — is resolved by the
// hint's qualifier (go_package / Go package clause, the import dir, the Python module, a dotted proto path),
// else unresolved (v6). A stub or fake server by path (`stubs/`, `fake.go`, `mockserver.go`) gives no server hint.
import { splitLines, fact, blankComments, lineIndex, isMinified, onePerKey, cleanUnresolved } from './lib/text.mjs';
import { isTestPath } from '../files.mjs';

const CODE_EXT_RE = /\.(go|java|kt|kts|py|ts|tsx|js|mjs|cjs|cs|rs)$/i;
// Hint table: [role, regex with ONE capture = the service name]. Add a framework = one line.
const HINTS = [
  ['server', /\bRegister(\w{1,100})Server\b/g],                       // Go grpc
  ['server', /\bUnimplemented(\w{1,100})Server\b/g],                  // Go grpc
  ['server', /\b(\w{1,100}?)(?:Coroutine)?ImplBase\b/g],              // Java / Kotlin grpc
  ['server', /\badd_(\w{1,100})Servicer_to_server\b/g],               // Python grpc
  ['server', /\b(\w{1,100})Servicer\b/g],                             // Python grpc base class
  ['server', /\b(\w{1,100})\.\1Base\b/g],                             // C# Grpc.Core
  ['server', /\b(\w{1,100})Server::new\b/g],                          // Rust tonic
  ['server', /\b\w{1,60}connect\.New(\w{1,100})Handler\b/g],          // connect-go
  ['server', /\.addService\(\s*[\w.]{0,200}?\b(\w{1,100})\.service\b/g], // grpc-js
  ['server', /\.add\(\s*(\w{1,100}?)(?:Definition|Service)\s*,/g],    // nice-grpc: server.add(XDefinition, impl) — never a DI `.add(UserService)`
  ['server', /\.addService\(\s*(?:\w{1,100}\.){0,4}(\w{1,100}?)Service\s*,/g], // grpc-tools static / ts-proto grpc-js: addService(services.XService, impl)
  ['client', /\bNew(\w{1,100})Client\b/g],                            // Go grpc, connect-go
  ['server', /\b\w{1,60}connect\.Register(\w{1,100}?)Handler\b/g],     // connect-go: xconnect.RegisterXHandler(server, impl)
  // grpc-gateway: RegisterXHandler(ctx, mux, conn) / …FromEndpoint dial the gRPC server. go-micro, dubbo-go triple and an aliased
  // connect-go package register a SERVER under the same name (`RegisterXHandler(srv, impl)`): a call is a client only when its first
  // argument is a context; a bare function value (a gateway's handler list) still is.
  ['client', /\b(?<!connect\.)Register(\w{1,100}?)Handler(?:FromEndpoint)?\b(?=\s{0,20}(?:[^\s(]|$)|\s{0,20}\(\s{0,20}(?:[\w.]{0,60}(?:ctx|Ctx|CTX)\w{0,40}\s{0,20},|context\.\w{1,40}\(|[\w.]{1,60}\.Context\(\s{0,20}\)))/g],
  ['client', /\b(\w{1,100})Grpc\.new(?:Blocking|Future)?Stub\b/g],    // Java grpc
  ['client', /\b\w{1,100}_pb2_grpc\.(\w{1,100}?)Stub\b/g],             // Python grpc (module-qualified)
  ['client', /\b(\w{1,100}?)(?:Coroutine)?Stub\b/g],                  // Python / Kotlin stubs
  ['client', /\b(\w{1,100})\.\1Client\b/g],                           // C# Grpc.Net.Client
  ['client', /\b(\w{1,100})Client::connect\b/g],                      // Rust tonic
  ['client', /\bcreateClient\(\s*(\w{1,100}?)(?:Definition|Service)\b/g], // nice-grpc
  ['client', /\bnew\s{1,20}(\w{1,100}?)Client\s{0,20}\(/g],              // ts-proto / grpc-js generic client
];
// Hints specific enough to report as unresolved when no local .proto defines the service.
const DISTINCT = /Grpc\.new|_pb2_grpc\.|\.(\w+)Client\b|Client::connect/;
// The header protoc / buf plugins stamp on generated code (Go, Python, Java, C#, JS, Rust).
// The stamp, not a hand-written `// DO NOT EDIT the port without …` (that file's hints still count).
const GENERATED_RE = /Code generated .{0,200}DO NOT EDIT|DO NOT EDIT!|<auto-generated|@generated|GrpcGenerated|javax\.annotation\.Generated/;
// A quoted gRPC full method name: "/<package>.<Service>/<Method>" (the capture is split at its last '.').
const FULL_METHOD_RE = /["'`]\/([A-Za-z_][\w.]{0,300})\/([A-Za-z_]\w{0,100})["'`]/g;
// A fake / mock server or a test helper outside a test path (internal/testutil, fakes/, mock_billing.go): no hint.
const FAKE_RE = /(?:^|\/)(?:[^/]*(?:fake|mock)[^/]*|testutils?|testing|testhelpers?)\/|(?:^|\/)(?:fake|mock)[_-][^/]*$|[_-](?:fake|mock)\.\w+$/i;
// …and no SERVER hint from a stub server or a fake by file name (`stubs/billing/main.go`, `internal/stubserver/`,
// `fake.go`, `fakes.py`, `FakeBilling.java`, `mockserver.go`): a second provider makes every call to the real one
// ambiguous. Client hints stay (a gRPC client is a "stub": `stubs/billing_client.py`).
const FAKE_SERVER_RE = /(?:^|\/)[^/]*stub[^/]*\/|(?:^|\/)(?:fake|mock|stub)[^/]*$/i;
// Go imports, one per line (`import pb "x/y"`, or inside an `import ( … )` block): alias → path. `[ \t]` only —
// a `\s` under /m crosses newlines, and a run of blank lines would be rescanned from every line start.
const GO_IMPORT_RE = /^[ \t]*(?:import[ \t]+)?(\w+[ \t]+)?"([\w.\-/]+)"[ \t\r]*$/gm;
// Python `from acme.billing.v2 import billing_pb2_grpc [as b]` / `import acme.billing.v2.billing_pb2_grpc as b`, and a JVM
// `import acme.billing.v2.BillingGrpc;`: the name → the dotted module's directory (`acme/billing/v2`).
const PY_FROM_RE = /^[ \t]*from[ \t]+([\w.]{1,300})[ \t]+import[ \t]+(\w{1,100})(?:[ \t]+as[ \t]+(\w{1,100}))?/gm;
const DOTTED_IMPORT_RE = /^[ \t]*import[ \t]+(?:static[ \t]+)?([\w.]{1,300})\.(\w{1,100})(?:[ \t]+as[ \t]+(\w{1,100}))?/gm;
const DECL_TAIL_RE = /(?:^|\W)(?:func|class|def|type|struct|interface|fn)$/;
/** true when the code right before a hint DEFINES a same-named symbol (`func NewPaymentClient(`, `func (s *srv)
 *  RegisterX…`, `class BillingStub:`, `type XServer struct`): the member's own wrapper, no hint. Reads only the
 *  tail of `before` (never a regex anchored at its end, which retries every start position). */
function declares(before) {
  let t = before.trimEnd();
  if (t.endsWith(')')) { // a Go method receiver: func (s *srv) Name
    const open = t.lastIndexOf('(');
    if (open === -1) return false;
    t = t.slice(0, open).trimEnd();
    return DECL_TAIL_RE.test(t.slice(-6)) && t.endsWith('func');
  }
  return DECL_TAIL_RE.test(t.slice(-10));
}
/** The identifier written right before the `.` that ends `before` (`billingv1.` → `billingv1`), else null. */
function qualifierOf(before) {
  let i = before.length - 1;
  while (i >= 0 && (before[i] === ' ' || before[i] === '\t')) i -= 1;
  if (before[i] !== '.') return null;
  i -= 1;
  const end = i + 1;
  while (i >= 0 && /\w/.test(before[i])) i -= 1;
  return end > i + 1 ? before.slice(i + 1, end) : null;
}

/** Records the full method names of one generated file: service → qualified name → [method sites]. */
function collectGenerated(rel, text, st) {
  st.gen ??= new Map();
  let lines = null;
  let lineOf = null;
  const slash = rel.lastIndexOf('/');
  // What a caller's qualifier can name: the Go package clause, the file's module name (`billing_pb2_grpc`).
  const tags = [/^package\s+(\w+)/m.exec(text)?.[1], rel.slice(slash + 1).replace(/\.\w+$/, '')].filter(Boolean);
  const dir = slash === -1 ? '' : rel.slice(0, slash);
  const add = (qualified, method, index, needle) => {
    const service = qualified.slice(qualified.lastIndexOf('.') + 1);
    if (!service) return;
    lines ??= splitLines(text);
    lineOf ??= lineIndex(text);
    if (!st.gen.has(service)) st.gen.set(service, new Map());
    const byName = st.gen.get(service);
    if (!byName.has(qualified)) byName.set(qualified, []);
    byName.get(qualified).push({ method, rel, lines, line: lineOf(index), needle, tags, dirs: [dir] });
  };
  for (const m of text.matchAll(FULL_METHOD_RE)) add(m[1], m[2], m.index, `/${m[1]}/${m[2]}`);
  // grpc-java (`SERVICE_NAME` + generateFullMethodName) and grpc-dotnet (`__ServiceName` + the method name)
  // never write the full name as one literal.
  const java = /\bSERVICE_NAME\s*=\s*"([\w.]{1,300})"/.exec(text)?.[1];
  for (const m of text.matchAll(/generateFullMethodName\(\s*(?:SERVICE_NAME|"([\w.]{1,300})")\s*,\s*"(\w{1,100})"\s*\)/g)) {
    const q = m[1] || java;
    if (q) add(q, m[2], m.index, `"${m[2]}"`);
  }
  const cs = /\b__ServiceName\s*=\s*"([\w.]{1,300})"/.exec(text)?.[1];
  if (cs) for (const m of text.matchAll(/\b__ServiceName\s*,\s*"(\w{1,100})"/g)) add(cs, m[1], m.index + m[0].length - m[1].length - 2, `"${m[1]}"`);
}

function parseProto(text) {
  const code = blankComments(text, { slash: true, quotes: '"\'' });
  const lineOf = lineIndex(code);
  const pkg = /\bpackage\s+([\w.]+)\s*;/.exec(code)?.[1] || '';
  const services = [];
  const SERVICE_RE = /\bservice\s+(\w+)\s*\{/g;
  let lastEnd = 0;
  for (const m of code.matchAll(SERVICE_RE)) {
    if (m.index < lastEnd) continue; // inside the previous service's body
    // body = up to the matching close brace (options blocks nest one level)
    let depth = 1;
    let i = m.index + m[0].length;
    for (; i < code.length && depth > 0; i += 1) { if (code[i] === '{') depth += 1; else if (code[i] === '}') depth -= 1; }
    lastEnd = i;
    const body = code.slice(m.index + m[0].length, i);
    const rpcs = [];
    for (const r of body.matchAll(/\brpc\s+(\w+)\s*\(/g)) rpcs.push({ name: r[1], line: lineOf(m.index + m[0].length + r.index) });
    services.push({ name: m[1], line: lineOf(m.index), rpcs });
  }
  // What a caller's qualifier can name when one bare service name is in several packages: the Go package
  // (`option go_package = "path;name"`, else the path's last segment), its import path, the Python modules.
  const go = /\boption\s+go_package\s*=\s*"([^"\s;]{0,300})(?:;(\w{1,100}))?"/.exec(code);
  const goPath = go?.[1] || '';
  return { pkg, services, goName: go?.[2] || goPath.slice(goPath.lastIndexOf('/') + 1), goPath };
}

function detect({ rel, text }, ctx) {
  const st = ctx.state;
  st.protos ??= [];
  st.hints ??= [];
  if (/\.proto$/i.test(rel)) {
    const p = parseProto(text);
    if (p.services.length) st.protos.push({ rel, lines: splitLines(text), ...p });
    return undefined;
  }
  if (isTestPath(rel) || isMinified(rel, text)) return undefined; // not the member's own server / client
  if (GENERATED_RE.test(text.slice(0, 4096))) { // protoc / buf output: no hint (it names both sides), maybe definitions
    collectGenerated(rel, text, st);
    return undefined;
  }
  if (FAKE_RE.test(rel)) return undefined; // a fake server beside the client is not the member's own server
  if (!/Server|Servicer|Base|Stub|Client|Handler|addService|\.add\(/.test(text)) return undefined; // cheap gate
  const fakeServer = FAKE_SERVER_RE.test(rel);
  const py = /\.py$/i.test(rel);
  const code = blankComments(text, { slash: !py, hash: py, quotes: '"\'`' }); // a comment naming a registration is no hint
  const lineOf = lineIndex(code);
  // Go imports: alias (or last path segment) → import path, so `pb.NewBillingClient` names the generated dir it calls;
  // `imps` (every import path, bounded) narrows a package clause several generated packages share.
  const imports = new Map();
  const imps = [];
  if (/\.go$/i.test(rel)) {
    for (const im of code.matchAll(GO_IMPORT_RE)) {
      imports.set(im[1]?.trim() || im[2].slice(im[2].lastIndexOf('/') + 1), im[2]);
      if (imps.length < 256) imps.push(im[2]);
    }
  } else if (py) {
    for (const im of code.matchAll(PY_FROM_RE)) imports.set(im[3] || im[2], im[1].replace(/\./g, '/'));
    for (const im of code.matchAll(DOTTED_IMPORT_RE)) imports.set(im[3] || im[2], im[1].replace(/\./g, '/'));
  } else if (/\.(?:java|kt)$/i.test(rel)) {
    for (const im of code.matchAll(DOTTED_IMPORT_RE)) imports.set(im[3] || im[2], im[1].replace(/\./g, '/'));
  }
  for (const [role, re] of HINTS) {
    if (role === 'server' && fakeServer) continue;
    for (const m of code.matchAll(re)) {
      const before = code.slice(Math.max(0, m.index - 240), m.index);
      if (declares(before)) continue;
      const qual = qualifierOf(before) ?? /^(\w+)\./.exec(m[0])?.[1] ?? null;
      // A dotted path written before the name (`proto.acme.billing.v1.Billing.service`) may end in its proto package.
      const at = m[0].lastIndexOf(m[1]);
      let from = at;
      while (from > 0 && /[\w.]/.test(m[0][from - 1])) from -= 1;
      const path = m[0].slice(from, at).split('.').filter(Boolean);
      st.hints.push({ role, service: m[1], rel, line: lineOf(m.index), match: m[0], qual, imp: qual ? imports.get(qual) ?? null : null, imps, path });
    }
  }
  return undefined;
}

function finish(ctx) {
  const st = ctx.state;
  const facts = [];
  const unresolved = [];
  const known = new Set();
  (st.hints || []).sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : a.line - b.line));
  const first = new Map(); // `${role}\u0000${service}` → its first hint, indexed once (never a scan per service)
  for (const h of st.hints || []) { const k = `${h.role}\u0000${h.service}`; if (!first.has(k)) first.set(k, h); }
  const all = new Map(); // `${role}\u0000${service}` → every hint
  for (const h of st.hints || []) { const k = `${h.role}\u0000${h.service}`; if (!all.has(k)) all.set(k, []); all.get(k).push(h); }
  // One bare name in several packages (buf output of a whole module: acme.billing.v1.Admin and acme.catalog.v1.Admin,
  // or v1 and v2 of one service — generated code or local .proto files alike): each hint picks the package its
  // qualifier names — the Go package clause / go_package name or the import dir its alias names, the Python module —
  // and a clause several packages share (`package pb`) is narrowed to the dirs the hint's file imports; never all
  // of them; none → one unresolved item and no fact. → Map(qualified → hint)
  const choose = (service, byName, role, hint, reason) => {
    const chosen = new Map();
    if (byName.size === 1) { chosen.set([...byName.keys()][0], hint); return chosen; }
    const by = new Map(); // `t:<tag>` / `s:<a dir's last two segments>` → qualified names (indexed once: never hints × sites)
    const put = (k, q) => { if (!by.has(k)) by.set(k, new Set()); by.get(k).add(q); };
    // A path can end in a package dir only through that dir's last segment: last segment → [dir, qualified] (a path
    // names a dir when it IS the dir or ends in `/<dir>` — one endsWith per candidate, never a join per suffix).
    const byLast = new Map();
    for (const [q, sites] of byName) {
      for (const g of sites) {
        for (const t of g.tags) put(`t:${t}`, q);
        for (const d of g.dirs) {
          if (!d) continue;
          const last = d.slice(d.lastIndexOf('/') + 1);
          if (!byLast.has(last)) byLast.set(last, []);
          byLast.get(last).push([d, q]);
          const two = d.split('/').slice(-2); if (two.length === 2) put(`s:${two.join('/')}`, q); // `billing/v2`
        }
      }
    }
    // `loose`: an import path whose last two segments are a package dir's (buf managed mode writes no go_package — the Go
    // path is `<prefix>/<dir under the module root>`; a Python / JVM module path) — only for the hint's own import.
    const inDirs = (paths, loose = false) => {
      const out = new Set();
      for (let p of paths) {
        let last = p.slice(p.lastIndexOf('/') + 1);
        // connect-go generates into `<go package dir>/<name>connect`
        if (!byLast.has(last) && last.endsWith('connect') && p.includes('/')) { p = p.slice(0, p.lastIndexOf('/')); last = p.slice(p.lastIndexOf('/') + 1); }
        if (!byLast.has(last)) continue;
        const before = out.size;
        for (const [d, q] of byLast.get(last)) if (p === d || p.endsWith(`/${d}`)) out.add(q);
        const i1 = p.lastIndexOf('/');
        if (loose && out.size === before && i1 !== -1) {
          const i2 = i1 > 0 ? p.lastIndexOf('/', i1 - 1) : -1;
          for (const q of by.get(`s:${p.slice(i2 + 1)}`) || []) out.add(q); // the path's last two segments
        }
      }
      return out;
    };
    const imported = new Map(); // rel → the packages its imports name (once per file)
    for (const h of all.get(`${role}\u0000${service}`)) {
      if (chosen.size === byName.size) break; // every package picked
      if (!h.qual && !h.path?.length) continue;
      // The import its qualifier names decides alone when it names one package (a tag can name several: `v1`, `pb`).
      const own = h.imp ? inDirs([h.imp], true) : new Set();
      if (own.size === 1) { const [q] = own; if (!chosen.has(q)) chosen.set(q, h); continue; }
      let hit = new Set(h.qual ? by.get(`t:${h.qual}`) : []);
      for (let i = 0; i < (h.path?.length || 0); i += 1) { const q = `${h.path.slice(i).join('.')}.${service}`; if (byName.has(q)) hit.add(q); }
      for (const q of own) hit.add(q);
      if (hit.size > 1 && h.imps?.length) {
        if (!imported.has(h.rel)) imported.set(h.rel, inDirs(h.imps));
        const narrowed = [...hit].filter((q) => imported.get(h.rel).has(q));
        if (narrowed.length) hit = new Set(narrowed);
      }
      if (hit.size === 1) { const [q] = hit; if (!chosen.has(q)) chosen.set(q, h); }
    }
    if (!chosen.size) unresolved.push({ kind: 'grpc', raw: `${hint.match} (${[...byName.keys()].join(', ')})`, file: hint.rel, line: hint.line, reason });
    return chosen;
  };
  const protoPkgs = new Map(); // bare name → Map(qualified → [{ tags, dirs }])
  for (const proto of st.protos || []) {
    const slash = proto.rel.lastIndexOf('/');
    const stem = proto.rel.slice(slash + 1).replace(/\.proto$/i, '');
    const site = { tags: [proto.goName, `${stem}_pb2_grpc`, `${stem}_pb2`].filter(Boolean), dirs: [proto.goPath, slash === -1 ? '' : proto.rel.slice(0, slash)] };
    for (const s of proto.services) {
      const q = proto.pkg ? `${proto.pkg}.${s.name}` : s.name;
      if (!protoPkgs.has(s.name)) protoPkgs.set(s.name, new Map());
      if (!protoPkgs.get(s.name).has(q)) protoPkgs.get(s.name).set(q, []);
      protoPkgs.get(s.name).get(q).push(site);
    }
  }
  const protoPick = new Map(); // `${role}\u0000${name}` → Map(qualified → hint), decided once per name
  const picked = (role, name, qualified) => {
    const k = `${role}\u0000${name}`;
    const hint = first.get(k);
    if (!hint) return undefined;
    if (!protoPick.has(k)) protoPick.set(k, choose(name, protoPkgs.get(name), role, hint, 'grpc service name in more than one package'));
    return protoPick.get(k).get(qualified);
  };
  for (const proto of st.protos || []) {
    for (const s of proto.services) {
      known.add(s.name);
      const qualified = proto.pkg ? `${proto.pkg}.${s.name}` : s.name;
      const server = picked('server', s.name, qualified);
      const client = picked('client', s.name, qualified);
      const emit = (dir, confidence, hint) => {
        for (const r of s.rpcs) {
          facts.push(fact({ kind: 'grpc', dir, key: `${qualified}/${r.name}`, rel: proto.rel, lines: proto.lines, line: r.line, needle: r.name,
            detail: `${dir === 'provides' ? 'server' : 'client'} ${hint.rel}:${hint.line}`, confidence }));
        }
      };
      if (server) emit('provides', 'exact', server);
      if (client) emit('consumes', 'exact', client);
      // Neither hint: a contracts repo or a vendored copy — the direction is unknown (a consume
      // here would join the implementer as an exact edge pointing the wrong way).
      // A package the hints did not pick stays silent (its name's hints chose another package, or none).
      if (!first.has(`server\u0000${s.name}`) && !first.has(`client\u0000${s.name}`)) unresolved.push({ kind: 'grpc', raw: `${qualified} (${s.rpcs.length} rpc)`, file: proto.rel, line: s.line, reason: 'grpc service without a server or client hint' });
    }
  }
  // Services defined only by vendored generated code: emitted for a service this member serves or
  // calls (the other services of a vendored client library stay silent).
  for (const [service, byName] of st.gen || []) {
    if (known.has(service)) continue;
    const server = first.get(`server\u0000${service}`);
    const client = first.get(`client\u0000${service}`);
    if (!server && !client) continue;
    known.add(service);
    const pick = new Map(); // role → Map(qualified → hint)
    for (const [role, hint] of [['server', server], ['client', client]]) {
      if (hint) pick.set(role, choose(service, byName, role, hint, 'grpc service name in more than one generated package'));
    }
    for (const [qualified, sites] of byName) {
      for (const g of sites) {
        for (const [dir, role] of [['provides', 'server'], ['consumes', 'client']]) {
          const hint = pick.get(role)?.get(qualified);
          if (!hint) continue;
          facts.push(fact({ kind: 'grpc', dir, key: `${qualified}/${g.method}`, rel: g.rel, lines: g.lines, line: g.line, needle: g.needle,
            detail: `${dir === 'provides' ? 'server' : 'client'} ${hint.rel}:${hint.line} (generated code)`, confidence: 'exact' }));
        }
      }
    }
  }
  const reported = new Set();
  for (const h of st.hints || []) {
    if (h.role !== 'client' || known.has(h.service) || !DISTINCT.test(h.match) || reported.has(h.service)) continue;
    reported.add(h.service);
    unresolved.push({ kind: 'grpc', raw: h.match, file: h.rel, line: h.line, reason: 'grpc client without a local .proto' });
  }
  return { facts: onePerKey(facts), unresolved: cleanUnresolved(st, null, unresolved) };
}

export default Object.freeze({
  id: 'api-proto',
  claims: (rel) => /\.proto$/i.test(rel) || CODE_EXT_RE.test(rel),
  detect,
  finish,
});
